version: '3'

services:
  elasticsearch:
    image: 'elasticsearch:5'
    environment:
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ports:
      - "9200:9200"
      - "9300:9300"

  web:
    image: rorcommunity/org-id:api
    ports:
      - "9292:80"
    environment:
      - ELASTIC_SEARCH=http://elasticsearch:9200
